### ISSUE TITLE
Cryptic error when running a solution whose "execution" command has a non-existing tool

### ISSUE THREAD

**Issue by rsalesc** [rsalesc/rbx#454]
When you edit the python `execution.command` to something like `python3x {executable}` to force a non-existing tool error, things crash with an unexpected error.

We should show a more informative error in this case (like we do for the compilation error case).

<img width="1045" height="569" alt="Image" src="https://github.com/user-attachments/assets/2d72c807-45bf-41d5-8072-c3d7683bb52d" />

This is probably introduced by #451 , and should be fixed, the error is non-sense. We should try to reproduce the exact same behavior with a modified env.rbx.yml that has a non-existing run command for some language.
